<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:client" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:client">
<types>
<xsd:schema targetNamespace="urn:client">
<xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
<xsd:import namespace="http://schemas.xmlsoap.org/wsdl/"/>
</xsd:schema>
</types>
<message name="getTeachersRequest">
<part name="teacher" type="xsd:string"/>
</message>
<message name="getTeachersResponse">
<part name="return" type="xsd:string"/>
</message>
<portType name="clientPortType">
<operation name="getTeachers">
<documentation>Get a list of teachers</documentation>
<input message="tns:getTeachersRequest"/>
<output message="tns:getTeachersResponse"/>
</operation>
</portType>
<binding name="clientBinding" type="tns:clientPortType">
<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
<operation name="getTeachers">
<soap:operation soapAction="urn:client#getTeachers" style="rpc"/>
<input>
<soap:body use="encoded" namespace="urn:client" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
</input>
<output>
<soap:body use="encoded" namespace="urn:client" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
</output>
</operation>
</binding>
<service name="client">
<port name="clientPort" binding="tns:clientBinding">
<soap:address location="http://localhost/si-api/soap-service.php"/>
</port>
</service>
</definitions>